import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  ru: {
    languageName: 'Русский',
    header: {
      home: 'Главная',
      clubs: 'Кружки',
      news: 'Новости',
      events: 'Мероприятия',
      about: 'О дворце',
      contacts: 'Контакты',
      login: 'Вход',
      register: 'Регистрация',
      logout: 'Выход',
      myApplications: 'Мои заявки',
      admin: 'Админ-панель',
      teacher: 'Кабинет учителя',
    },
    footer: {
      title: 'Дворец школьников Digital Urpaq',
      description: 'Информационный портал Петропавловского дворца школьников. Образовательные программы, кружки, мероприятия и новости для школьников и их родителей.',
      nav: ['Главная', 'Кружки', 'Новости', 'Мероприятия', 'О дворце'],
      copyright: '© 2026 Дворец школьников «Digital Urpaq». Все права защищены.',
    },
    home: {
      portalLabel: 'Портал Дворца школьников',
      heroTitle: 'Образование, кружки и события в Digital Urpaq',
      heroText: 'Удобный портал для школьников, родителей и преподавателей: выбирайте кружки, следите за новостями и планируйте участие в мероприятиях.',
      clubsButton: 'Смотреть кружки',
      eventsButton: 'Календарь событий',
      currentNowTitle: 'Актуально сейчас',
      currentNowText: 'Набор на летние курсы открыт. Программы по робототехнике, цифровому дизайну и биотехнологиям начинаются уже в июне.',
      nextMeetingTitle: 'Следующее занятие',
      nextMeetingValue: '29 мая, 16:00',
      nextProgramTitle: 'Программа',
      nextProgramValue: 'Веб-разработка для школьников',
      directionsTitle: 'Популярные кружки и учебные программы',
      directions: [
        {
          title: 'IT и программирование',
          description: 'Курсы по веб-разработке, программированию и цифровым технологиям.',
        },
        {
          title: 'Биотехнологии',
          description: 'Лабораторные проекты, экология и практическая биология.',
        },
        {
          title: 'Творчество',
          description: 'Дизайн, медиа, музыка и художественные мастерские.',
        },
        {
          title: 'Робототехника',
          description: 'Сборка и программирование роботов для соревнований.',
        },
      ],
      sectionTitle: 'Сферы развития',
      sections: [
        {
          title: 'Образование',
          description: 'От программирования до науки — современный подход и практические проекты.',
        },
        {
          title: 'События',
          description: 'Календарь мастер-классов, конкурсов и открытых уроков для школьников.',
        },
        {
          title: 'Новости',
          description: 'Все важные обновления дворца школьников в одном месте.',
        },
      ],
      newsTitle: 'Последние новости',
      newsSubtitle: 'Смотрите свежие публикации о достижениях учеников и новых программах.',
      noNews: 'Новостей пока нет.',
      readMore: 'Подробнее →',
      telegramTitle: 'Telegram-уведомления',
      telegramText: 'Подписывайтесь на обновления и получайте сообщения о новых кружках, событиях и статусе заявок в Telegram.',
      telegramButton: 'Открыть бот',
      telegramLink: 'https://t.me/du_notifications_bot',
      telegramInstructions: [
        'Откроюте Telegram и найдите бота @du_notifications_bot.',
        'Нажмите /start для запуска.',
        'Получайте уведомления о новых кружках, мероприятиях и заявках.',
      ],
      videoTitle: 'Видео-тур по проектам',
      videoText: 'Посмотрите, как проходят занятия, мастер-классы и презентации ученических проектов.',
    },
    clubs: {
      title: 'Современные направления для школьников',
      description: 'Найдите кружок по интересам: от IT-проектов до творческих студий, от науки до робототехники.',
      directionsTitle: 'Направления',
      groups: ['IT', 'Биотехнологии', 'Творчество', 'Робототехника', 'Наука'],
      searchPlaceholder: 'Поиск кружков',
      noResults: 'Кружков не найдено — попробуйте изменить фильтр.',
      advantagesTitle: 'Преимущества',
      advantages: [
        'Актуальная информация о кружках и направлениях.',
        'Фильтрация по категориям и расписанию.',
        'Удобный доступ к новостям и мероприятиям.',
      ],
      portalTitle: 'Современный портал',
      portalText: 'Для всех школьников Петропавловска',
    },
    about: {
      title: 'Digital Urpaq — образовательный портал дворца школьников',
      description: 'Платформа объединяет информацию о кружках, мероприятиях, новостях и документах для учеников, родителей и преподавателей.',
      stats: [
        { label: 'Направлений', value: '45+' },
        { label: 'Кружков', value: '120' },
        { label: 'Участников', value: '2300+' },
      ],
      missionTitle: 'Создать удобный доступ к дополнительному образованию',
      missionText: 'Digital Urpaq помогает школьникам найти кружок по интересам, узнать о событиях дворца и оставаться в курсе важных новостей.',
      featuresTitle: 'Наши возможности',
      features: [
        'Поиск кружков и направлений по интересам.',
        'Календарь мастер-классов и конкурсов.',
        'Новости о достижениях учеников и проектах.',
        'Поддержка коммуникации между учениками и преподавателями.',
      ],
      audience: [
        { title: 'Для учеников', description: 'Выбирайте кружки, подавайте заявки и следите за результатами.' },
        { title: 'Для преподавателей', description: 'Добавляйте кружки, управляйте набором и общайтесь с участниками.' },
        { title: 'Для родителей', description: 'Следите за расписаниями и событиями для вашего ребенка.' },
      ],
      ctaTitle: 'Откройте новый кружок в Digital Urpaq',
      ctaButton: 'Посмотреть кружки',
    },
    news: {
      title: 'Актуальные новости Digital Urpaq',
      description: 'Читайте о новых программах, конкурсах, достижениях школьников и важных событиях.',
      empty: 'Новостей пока нет.',
      achievementLabel: 'Достижение',
      newsLabel: 'Новость',
      details: 'Подробнее',
    },
    events: {
      title: 'Анонсы событий Digital Urpaq',
      description: 'Смотрите расписание мастер-классов, открытых дней и проектных конкурсов.',
      calendarTitle: 'Календарь событий',
    },
    contacts: {
      title: 'Контакты',
      subtitle: 'Свяжитесь с нами для вопросов по работе портала и регистрации кружков.',
      supportTitle: 'Поддержка',
      supportText: 'Наша команда готова помочь в рабочие дни с 9:00 до 18:00.',
      addressTitle: 'Адрес',
      addressText: 'г. Петропавловск, ул. Ж. Жабаева, 55А',
      emailLabel: 'Email',
      phoneLabel: 'Телефон',
      telegramTitle: 'Telegram-бот',
      telegramText: 'Откройте бота, чтобы получать уведомления о новых кружках и статусе заявок.',
      telegramButton: 'Открыть бот',
      telegramLink: 'https://t.me/du_notifications_bot',
      telegramInstructions: [
        'Откройте Telegram и найдите бота @du_notifications_bot.',
        'Нажмите /start для запуска.',
        'Получайте уведомления о новых кружках, мероприятиях и заявках.',
      ],
      mapLabel: 'Карта расположения',
    },
    auth: {
      loginTitle: 'Вход',
      registerTitle: 'Регистрация',
      emailLabel: 'Email',
      passwordLabel: 'Пароль',
      fullNameLabel: 'ФИО',
      phoneLabel: 'Телефон',
      ageLabel: 'Возраст',
      loginButton: 'Войти',
      registerButton: 'Зарегистрироваться',
      noAccount: 'Нет аккаунта?',
      haveAccount: 'Уже есть аккаунт?',
      signUp: 'Зарегистрируйтесь',
      signIn: 'Войдите',
      loading: 'Загрузка...',
      requiredFields: 'Заполните все обязательные поля',
      loginToApply: 'Войдите для подачи заявки',
      studentOnly: 'Только студенты могут подавать заявки',
      applyButton: 'Подать заявку',
      applying: 'Подача заявки...',
      appliedSuccess: 'Заявка подана успешно!',
      commentLabel: 'Комментарий (опционально)',
      commentPlaceholder: 'Расскажите о себе или ваших целях',
    },
    documents: {
      title: 'Документы',
      description: 'Полезные документы и важная информация для участников платформы.',
      openDocument: 'Открыть документ',
      items: [
        { title: 'Положение о кружках', description: 'Документ с правилами регистрации и участия в кружках.', url: '#' },
        { title: 'Политика конфиденциальности', description: 'Описание того, как мы обрабатываем персональные данные.', url: '/privacy' },
        { title: 'Пользовательское соглашение', description: 'Условия использования портала Digital Urpaq.', url: '/terms' },
      ],
    },
    privacy: {
      title: 'Политика конфиденциальности',
      intro: 'Digital Urpaq уважает вашу приватность. Мы собираем только необходимые данные для регистрации, подачи заявок и управления кружками.',
      items: [
        'Мы не передаем личные данные третьим лицам без вашего согласия.',
        'Данные используются только для работы портала и улучшения сервиса.',
        'Вы можете запросить удаление своих данных через службу поддержки.',
      ],
      contact: 'Если у вас есть вопросы по обработке данных, напишите на info@digitalurpaq.kz.',
    },
    terms: {
      title: 'Условия использования',
      intro: 'Используя Digital Urpaq, вы соглашаетесь с правилами работы портала, порядком подачи заявок и внутренними нормами общения.',
      items: [
        'Регистрация и заполнение профиля должны быть правдивыми.',
        'Запрещено публиковать нежелательный или оскорбительный контент.',
        'Администрация оставляет за собой право блокировать учетные записи при нарушениях.',
      ],
      contact: 'Для вопросов об условиях использования обратитесь по адресу info@digitalurpaq.kz.',
    },
    applications: {
      title: 'Мои заявки',
      noApplications: 'У вас нет заявок',
      cta: 'Подать заявку',
      statusLabel: 'Статус',
      dateLabel: 'Дата подачи',
      commentLabel: 'Ваш комментарий:',
      cancel: 'Отменить',
      cancelConfirm: 'Вы уверены?',
      canceled: 'Заявка отменена',
      cancelError: 'Ошибка при отмене заявки',
      statuses: {
        new: 'Новая',
        pending: 'На рассмотрении',
        approved: 'Одобрена',
        rejected: 'Отклонена',
      },
      studentOnly: 'Только студенты могут подавать заявки',
    },
    clubDetail: {
      infoTitle: 'Информация',
      descriptionTitle: 'Описание',
      venueLabel: 'Место проведения',
      scheduleLabel: 'Расписание',
      directionLabel: 'Направление',
      ageLabel: 'Возраст',
      teacherLabel: 'Преподаватель',
      statusOpen: '✓ Открыт',
      statusClosed: '✗ Закрыт',
      spotsLabel: 'Свободные места',
      closedMessage: 'Набор в этот кружок закрыт: мест {current}/{max}.',
      commentLabel: 'Комментарий (опционально)',
      commentPlaceholder: 'Расскажите о себе или ваших целях',
      applyButton: 'Подать заявку',
      applyingButton: 'Подача заявки...',
      appliedButton: '✓ Заявка подана',
      loginToApply: 'Войдите для подачи заявки',
      studentOnly: 'Только студенты могут подавать заявки',
      registeredLabel: 'Зарегистрировано',
      placesLabel: 'Мест',
      viewsLabel: 'Просмотров',
      ratingLabel: 'Рейтинг',
    },
  },
  kz: {
    languageName: 'Қазақша',
    header: {
      home: 'Басты',
      clubs: 'Үйірмелер',
      news: 'Жаңалықтар',
      events: 'Іс-шаралар',
      about: 'Турында',
      contacts: 'Байланыс',
      login: 'Кіру',
      register: 'Тіркелу',
      logout: 'Шығу',
      myApplications: 'Өтініштерім',
      admin: 'Әкімшілік',
      teacher: 'Мұғалім бөлімі',
    },
    footer: {
      title: 'Digital Urpaq Оқушылар сарайы',
      description: 'Петропавл оқушылар сарайының ақпараттық порталы. Оқу бағдарламалары, үйірмелер, іс-шаралар және жаңалықтар.',
      nav: ['Басты', 'Үйірмелер', 'Жаңалықтар', 'Іс-шаралар', 'Турында'],
      copyright: '© 2026 Digital Urpaq. Барлық құқықтар қорғалған.',
    },
    home: {
      portalLabel: 'Оқушылар сарайы порталы',
      heroTitle: 'Digital Urpaq-та білім, үйірмелер және іс-шаралар',
      heroText: 'Мектеп оқушыларына, ата-аналарға және мұғалімдерге арналған ыңғайлы портал: үйірмелерді таңдаңыз, жаңалықтарды қадағалаңыз және іс-шараларға жоспар құрыңыз.',
      clubsButton: 'Үйірмелерді қарау',
      eventsButton: 'Іс-шаралар күнтізбесі',
      currentNowTitle: 'Қазір өзекті',
      currentNowText: 'Жазғы курсқа қабылдау ашық. Робототехника, сандық дизайн және биотехнологиялар бағдарламалары маусым айында басталады.',
      nextMeetingTitle: 'Келесі сабақ',
      nextMeetingValue: '29 мамыр, 16:00',
      nextProgramTitle: 'Бағдарлама',
      nextProgramValue: 'Мектеп оқушыларына веб-даму',
      directionsTitle: 'Таңдаулы үйірмелер мен оқу бағдарламалары',
      directions: [
        {
          title: 'IT және бағдарламалау',
          description: 'Веб-даму, бағдарламалау және цифрлық технологиялар курстары.',
        },
        {
          title: 'Биотехнологиялар',
          description: 'Зертханалық жобалар, экология және практикалық биология.',
        },
        {
          title: 'Шығармашылық',
          description: 'Дизайн, медиа, музыка және көркем шеберханалар.',
        },
        {
          title: 'Робототехника',
          description: 'Роботтарды құрастыру және жарыстарға бағдарламалау.',
        },
      ],
      sectionTitle: 'Өркендеу бағыттары',
      sections: [
        {
          title: 'Білім',
          description: 'Бағдарламалаудан ғылымға дейін — заманауи тәсіл және практикалық жобалар.',
        },
        {
          title: 'Іс-шаралар',
          description: 'Мектеп оқушыларына арналған шеберлік сыныптар, жарыстар және ашық сабақтар күнтізбесі.',
        },
        {
          title: 'Жаңалықтар',
          description: 'Оқушылар сарайының маңызды жаңалықтары бір жерде.',
        },
      ],
      newsTitle: 'Соңғы жаңалықтар',
      newsSubtitle: 'Оқушылар жетістіктері мен жаңа бағдарламалар туралы жарияланымдарды қараңыз.',
      noNews: 'Әлі жаңалықтар жоқ.',
      readMore: 'Толығырақ →',
      telegramTitle: 'Telegram-хабарламалар',
      telegramText: 'Жаңартуларға жазылыңыз және үйірмелер, іс-шаралар және өтініш мәртебесі туралы хабарламалар алыңыз.',
      telegramButton: 'Ботты ашу',
      telegramLink: 'https://t.me/du_notifications_bot',
      telegramInstructions: [
        'Telegram-ды ашып, @du_notifications_bot ботын табыңыз.',
        '/start батырмасын басыңыз.',
        'Үйірмелер мен өтініштердің мәртебесі туралы хабарламалар алыңыз.',
      ],
      videoTitle: 'Жоба бойынша бейнетур',
      videoText: 'Сабақтардың, шеберлік сыныптардың және оқушы жобаларының таныстырылымдарын қараңыз.',
    },
    clubs: {
      title: 'Мектеп оқушыларына арналған заманауи бағыттар',
      description: 'Үйірмелерді қызығушылық бойынша табыңыз: IT-жобалардан шығармашылық студияларға, ғылымнан робототехникаға дейін.',
      directionsTitle: 'Бағыттар',
      groups: ['IT', 'Биотехнология', 'Шығармашылық', 'Робототехника', 'Ғылым'],
      searchPlaceholder: 'Үйірмелерді іздеу',
      noResults: 'Үйірмелер табылмады — сүзгіні өзгертіп көріңіз.',
      advantagesTitle: 'Артықшылықтар',
      advantages: [
        'Үйірмелер мен бағыттар туралы өзекті ақпарат.',
        'Санаттар мен кесте бойынша сүзу.',
        'Жаңалықтар мен іс-шараларға оңай қол жетімділік.',
      ],
      portalTitle: 'Заманауи портал',
      portalText: 'Петропавл оқушылары үшін',
    },
    about: {
      title: 'Digital Urpaq — оқушылар сарайының білім беру порталы',
      description: 'Платформа оқушыларға, ата-аналарға және мұғалімдерге арналған үйірмелер, іс-шаралар, жаңалықтар және құжаттар туралы ақпаратты біріктіреді.',
      stats: [
        { label: 'Бағыттар', value: '45+' },
        { label: 'Үйірмелер', value: '120' },
        { label: 'Қатысушылар', value: '2300+' },
      ],
      missionTitle: 'Қосымша білімге оңай қол жеткізуді қамтамасыз ету',
      missionText: 'Digital Urpaq оқушыларға қызығушылық бойынша үйірмелерді табуға, іс-шаралар туралы білуге және маңызды жаңалықтарды бақылауға көмектеседі.',
      featuresTitle: 'Біздің мүмкіндіктер',
      features: [
        'Қызығушылық бойынша үйірмелер мен бағыттарды іздеу.',
        'Шеберлік сыныптар мен конкурстар күнтізбесі.',
        'Оқушылардың жетістіктері мен жобалары туралы жаңалықтар.',
        'Оқушылар мен мұғалімдер арасындағы байланысқа қолдау.',
      ],
      audience: [
        { title: 'Оқушылар үшін', description: 'Үйірмелерді таңдап, өтініштерді жіберіп, нәтижелерді қадағалаңыз.' },
        { title: 'Мұғалімдер үшін', description: 'Үйірмелерді қосып, қабылдауды басқарып, қатысушылармен сөйлесіңіз.' },
        { title: 'Ата-аналар үшін', description: 'Балаңыздың кестесін және іс-шараларды бақылаңыз.' },
      ],
      ctaTitle: 'Digital Urpaq-та жаңа үйірмені ашыңыз',
      ctaButton: 'Үйірмелерді қарау',
    },
    news: {
      title: 'Актуалды жаңалықтар Digital Urpaq',
      description: 'Жаңа бағдарламалар, жарыстар, оқушы жетістіктері және маңызды оқиғалар туралы оқыңыз.',
      empty: 'Әлі жаңалықтар жоқ.',
      achievementLabel: 'Жетістік',
      newsLabel: 'Жаңалық',
      details: 'Толығырақ',
    },
    events: {
      title: 'Digital Urpaq іс-шаралары',
      description: 'Шеберлік сыныптар, ашық күндер және жоба конкурстары кестесін қараңыз.',
      calendarTitle: 'Іс-шаралар күнтізбесі',
    },
    contacts: {
      title: 'Байланыс',
      subtitle: 'Порталдың жұмысы және үйірмелерге тіркелу бойынша сұрақтарыңызға жауап алыңыз.',
      supportTitle: 'Қолдау',
      supportText: 'Біздің команда жұмыс күндері сағат 9:00-18:00 аралығында көмектесуге дайын.',
      addressTitle: 'Мекенжай',
      addressText: 'Петропавл қаласы, Ж. Жабаев көшесі, 55А',
      emailLabel: 'Электрондық пошта',
      phoneLabel: 'Телефон',
      telegramTitle: 'Telegram-бот',
      telegramText: 'Үйірмелер мен өтініш мәртебелері туралы хабарламалар алу үшін ботты ашыңыз.',
      telegramButton: 'Ботты ашу',
      telegramLink: 'https://t.me/du_notifications_bot',
      telegramInstructions: [
        'Telegram-ды ашып, @du_notifications_bot ботын табыңыз.',
        '/start батырмасын басыңыз.',
        'Үйірмелер мен өтініштердің мәртебесі туралы хабарламалар алыңыз.',
      ],
      mapLabel: 'Орналасқан жер картасы',
    },
    auth: {
      loginTitle: 'Кіру',
      registerTitle: 'Тіркелу',
      emailLabel: 'Email',
      passwordLabel: 'Құпия сөз',
      fullNameLabel: 'Толық аты-жөні',
      phoneLabel: 'Телефон',
      ageLabel: 'Жасы',
      loginButton: 'Кіру',
      registerButton: 'Тіркелу',
      noAccount: 'Тіркелген жоқсыз ба?',
      haveAccount: 'Есебі бар ма?',
      signUp: 'Тіркеліңіз',
      signIn: 'Кіру',
      loading: 'Жүктелуде...',
      requiredFields: 'Барлық міндетті өрістерді толтырыңыз',
      loginToApply: 'Өтініш беру үшін кіріңіз',
      studentOnly: 'Тек оқушылар өтініш бере алады',
      applyButton: 'Өтініш беру',
      applying: 'Өтініш жіберілуде...',
      appliedSuccess: 'Өтініш сәтті жіберілді!',
      commentLabel: 'Түсініктеме (міндетті емес)',
      commentPlaceholder: 'Өзіңіз туралы немесе мақсаттарыңыз туралы жазыңыз',
    },
    documents: {
      title: 'Құжаттар',
      description: 'Платформа қатысушылары үшін пайдалы құжаттар мен маңызды ақпарат.',
      openDocument: 'Құжатты ашу',
      items: [
        { title: 'Үйірме ережелері', description: 'Үйірмелерге тіркелу және қатысу ережелері туралы құжат.', url: '#' },
        { title: 'Құпиялылық саясаты', description: 'Жеке деректерді қалай өңдейтіміз туралы ақпарат.', url: '/privacy' },
        { title: 'Қолданушы келісімі', description: 'Digital Urpaq порталынын пайдалану шарттары.', url: '/terms' },
      ],
    },
    privacy: {
      title: 'Құпиялылық саясаты',
      intro: 'Digital Urpaq сіздің құпиялылығыңызды құрметтейді. Біз тіркелу, өтініштер және үйірмелерді басқару үшін қажет деректерді ғана жинаймыз.',
      items: [
        'Жеке деректеріңізді сіздің келісіміңізсіз үшінші тұлғаларға бермейміз.',
        'Деректер тек порталдың жұмысын және қызметті жақсартуды қамтамасыз ету үшін пайдаланылады.',
        'Деректерді жоюды қолдау қызметі арқылы сұрауға болады.',
      ],
      contact: 'Деректерді өңдеу туралы сұрақтарыңыз болса, info@digitalurpaq.kz мекенжайына жазыңыз.',
    },
    terms: {
      title: 'Пайдалану шарттары',
      intro: 'Digital Urpaq-ты пайдалана отырып, сіз портал ережелерімен, өтініш процедураларымен және қоғамдастық стандарттарымен келісесіз.',
      items: [
        'Тіркелу және профиль деректері шынайы болуы тиіс.',
        'Спам немесе қорлаушы контент жариялауға тыйым салынады.',
        'Ережелерді бұзған жағдайда әкімшілік есептік жазбаны бұғаттай алады.',
      ],
      contact: 'Пайдалану шарттары туралы сұрақтар үшін info@digitalurpaq.kz мекенжайымен хабарласыңыз.',
    },
    applications: {
      title: 'Менің өтініштерім',
      noApplications: 'Сізде өтініштер жоқ',
      cta: 'Өтініш беру',
      statusLabel: 'Статус',
      dateLabel: 'Жіберілген күні',
      commentLabel: 'Сіздің пікіріңіз:',
      cancel: 'Бас тарту',
      cancelConfirm: 'Сіз сенімдісіз бе?',
      canceled: 'Өтініш қайтарылды',
      cancelError: 'Өтінішті қайтару кезінде қате шықты',
      statuses: {
        new: 'Жаңа',
        pending: 'Қарауда',
        approved: 'Қабылданды',
        rejected: 'Қайтарылды',
      },
      studentOnly: 'Тек оқушылар өтініш бере алады',
    },
    clubDetail: {
      infoTitle: 'Ақпарат',
      descriptionTitle: 'Сипаттама',
      venueLabel: 'Өткізілетін орын',
      scheduleLabel: 'Кесте',
      directionLabel: 'Бағыт',
      ageLabel: 'Жас',
      teacherLabel: 'Мұғалім',
      statusOpen: '✓ Ашық',
      statusClosed: '✗ Жабық',
      spotsLabel: 'Бос орындар',
      closedMessage: 'Бұл үйірмеге қабылдау жабылды: {current}/{max} орын.',
      commentLabel: 'Түсініктеме (міндетті емес)',
      commentPlaceholder: 'Өзіңіз туралы немесе мақсаттарыңыз туралы жазыңыз',
      applyButton: 'Өтініш беру',
      applyingButton: 'Өтініш жіберіліп жатыр...',
      appliedButton: '✓ Өтініш жіберілді',
      loginToApply: 'Өтініш беру үшін кіріңіз',
      studentOnly: 'Тек оқушылар өтініш бере алады',
      registeredLabel: 'Тіркелген',
      placesLabel: 'Орын',
      viewsLabel: 'Көрулер',
      ratingLabel: 'Баға',
    },
  },
  en: {
    languageName: 'English',
    header: {
      home: 'Home',
      clubs: 'Clubs',
      news: 'News',
      events: 'Events',
      about: 'About',
      contacts: 'Contacts',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
      myApplications: 'My Applications',
      admin: 'Admin Panel',
      teacher: 'Teacher Area',
    },
    footer: {
      title: 'Digital Urpaq Student Palace',
      description: 'Information portal of the Petropavlovsk Student Palace. Educational programs, clubs, events and news for students and parents.',
      nav: ['Home', 'Clubs', 'News', 'Events', 'About'],
      copyright: '© 2026 Digital Urpaq. All rights reserved.',
    },
    home: {
      portalLabel: 'Student Palace Portal',
      heroTitle: 'Education, clubs and events at Digital Urpaq',
      heroText: 'A convenient portal for students, parents and teachers: choose clubs, follow news, and plan participation in events.',
      clubsButton: 'Explore clubs',
      eventsButton: 'View events',
      currentNowTitle: 'Happening now',
      currentNowText: 'Summer program enrollment is open. Robotics, digital design and biotechnology sessions begin in June.',
      nextMeetingTitle: 'Next session',
      nextMeetingValue: 'May 29, 16:00',
      nextProgramTitle: 'Program',
      nextProgramValue: 'Web development for students',
      directionsTitle: 'Popular clubs and programs',
      directions: [
        { title: 'IT and programming', description: 'Courses in web development, programming and digital technologies.' },
        { title: 'Biotechnology', description: 'Laboratory projects, ecology and practical biology.' },
        { title: 'Creativity', description: 'Design, media, music and art workshops.' },
        { title: 'Robotics', description: 'Building and programming robots for contests.' },
      ],
      sectionTitle: 'Areas of growth',
      sections: [
        { title: 'Learning', description: 'From programming to science — modern learning with practical projects.' },
        { title: 'Events', description: 'Calendar of masterclasses, competitions and open lessons for students.' },
        { title: 'News', description: 'All important Student Palace updates in one place.' },
      ],
      newsTitle: 'Latest news',
      newsSubtitle: 'See fresh stories about student achievements and new programs.',
      noNews: 'There are no news items yet.',
      readMore: 'Read more →',
      telegramTitle: 'Telegram notifications',
      telegramText: 'Subscribe for updates and receive messages about new clubs, events and application status in Telegram.',
      telegramButton: 'Open bot',
      telegramLink: 'https://t.me/du_notifications_bot',
      videoTitle: 'Video tour of projects',
      videoText: 'Watch how classes, workshops and student project presentations take place.',
    },
    clubs: {
      title: 'Modern programs for students',
      description: 'Find a club by interest: from IT projects to creative studios, from science to robotics.',
      directionsTitle: 'Categories',
      groups: ['IT', 'Biotechnology', 'Creative', 'Robotics', 'Science'],
      searchPlaceholder: 'Search clubs',
      noResults: 'No clubs found — try changing your filters.',
      advantagesTitle: 'Benefits',
      advantages: ['Up-to-date information about clubs and tracks.', 'Filter by category and schedule.', 'Easy access to news and events.'],
      portalTitle: 'Modern portal',
      portalText: 'For all Petropavlovsk students',
    },
    about: {
      title: 'Digital Urpaq — educational portal of the student palace',
      description: 'The platform brings together information about clubs, events, news and documents for students, parents and teachers.',
      stats: [ { label: 'Tracks', value: '45+' }, { label: 'Clubs', value: '120' }, { label: 'Participants', value: '2300+' } ],
      missionTitle: 'Make additional education easy to access',
      missionText: 'Digital Urpaq helps students find clubs by interest, learn about events and keep up with important news.',
      featuresTitle: 'What we offer',
      features: [ 'Search clubs and tracks by interest.', 'Calendar of workshops and competitions.', 'News about student achievements and projects.', 'Support communication between students and teachers.' ],
      audience: [ { title: 'For students', description: 'Choose clubs, submit applications and track results.' }, { title: 'For teachers', description: 'Create clubs, manage enrollment and communicate with participants.' }, { title: 'For parents', description: 'Monitor your child’s schedule and events.' } ],
      ctaTitle: 'Start a new club in Digital Urpaq',
      ctaButton: 'Explore clubs',
    },
    news: { title: 'Digital Urpaq news', description: 'Read about new programs, competitions, student achievements and important events.', empty: 'No news yet.', achievementLabel: 'Achievement', newsLabel: 'News', details: 'Read more' },
    events: { title: 'Digital Urpaq events', description: 'See the schedule of workshops, open days and project competitions.', calendarTitle: 'Events calendar' },
    contacts: {
      title: 'Contacts',
      subtitle: 'Contact us for questions about the portal and club registration.',
      supportTitle: 'Support',
      supportText: 'Our team is ready to help on weekdays from 9:00 to 18:00.',
      addressTitle: 'Address',
      addressText: 'Petropavlovsk, Z. Zhabaev St., 55A',
      emailLabel: 'Email',
      phoneLabel: 'Phone',
      telegramTitle: 'Telegram bot',
      telegramText: 'Open the bot to receive notifications about clubs and application status.',
      telegramButton: 'Open bot',
      telegramLink: 'https://t.me/du_notifications_bot',
      mapLabel: 'Location map',
    },
    auth: {
      loginTitle: 'Login',
      registerTitle: 'Register',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      fullNameLabel: 'Full name',
      phoneLabel: 'Phone',
      ageLabel: 'Age',
      loginButton: 'Login',
      registerButton: 'Register',
      noAccount: 'No account?',
      haveAccount: 'Already have an account?',
      signUp: 'Sign up',
      signIn: 'Sign in',
      loading: 'Loading...',
      requiredFields: 'Please fill in all required fields',
      loginToApply: 'Login to apply',
      studentOnly: 'Only students can apply',
      applyButton: 'Apply for club',
      applying: 'Submitting application...',
      appliedSuccess: 'Application submitted successfully!',
      commentLabel: 'Comment (optional)',
      commentPlaceholder: 'Tell us about yourself or your goals',
    },
    documents: {
      title: 'Documents',
      description: 'Useful documents and important information for platform participants.',
      openDocument: 'Open document',
      items: [ { title: 'Club rules', description: 'A document with rules for registration and participation in clubs.', url: '#' }, { title: 'Privacy policy', description: 'Information on how we process personal data.', url: '/privacy' }, { title: 'User agreement', description: 'Terms of use for the Digital Urpaq portal.', url: '/terms' } ],
    },
    privacy: {
      title: 'Privacy policy',
      intro: 'Digital Urpaq respects your privacy. We only collect the data required for registration, applications, and club management.',
      items: [ 'We do not share personal data with third parties without your consent.', 'Data is used only to operate the portal and improve service.', 'You can request deletion of your data through support.' ],
      contact: 'If you have questions about data processing, write to info@digitalurpaq.kz.',
    },
    terms: {
      title: 'Terms of use',
      intro: 'By using Digital Urpaq, you agree to the portal rules, application procedures, and community standards.',
      items: [ 'Registration and profile information must be truthful.', 'Posting spam or offensive content is prohibited.', 'Administration may block accounts for violations.' ],
      contact: 'For questions about terms of use, contact info@digitalurpaq.kz.',
    },
    applications: {
      title: 'My applications',
      noApplications: 'You have no applications',
      cta: 'Submit an application',
      statusLabel: 'Status',
      dateLabel: 'Submitted on',
      commentLabel: 'Your comment:',
      cancel: 'Cancel',
      cancelConfirm: 'Are you sure?',
      canceled: 'Application cancelled',
      cancelError: 'Error cancelling application',
      statuses: { new: 'New', pending: 'Pending', approved: 'Approved', rejected: 'Rejected' },
      studentOnly: 'Only students can submit applications',
    },
    clubDetail: {
      infoTitle: 'Information',
      descriptionTitle: 'Description',
      venueLabel: 'Venue',
      scheduleLabel: 'Schedule',
      directionLabel: 'Direction',
      ageLabel: 'Age',
      teacherLabel: 'Teacher',
      statusOpen: '✓ Open',
      statusClosed: '✗ Closed',
      spotsLabel: 'Available spots',
      closedMessage: 'Enrollment is closed for this club: {current}/{max} spots.',
      commentLabel: 'Comment (optional)',
      commentPlaceholder: 'Tell us about yourself or your goals',
      applyButton: 'Apply for club',
      applyingButton: 'Applying...',
      appliedButton: '✓ Application sent',
      loginToApply: 'Login to apply',
      studentOnly: 'Only students can apply',
      registeredLabel: 'Registered',
      placesLabel: 'Places',
      viewsLabel: 'Views',
      ratingLabel: 'Rating',
    },
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [locale, setLocale] = useState('ru');

  useEffect(() => {
    const savedLocale = localStorage.getItem('language');
    if (savedLocale && translations[savedLocale]) {
      setLocale(savedLocale);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', locale);
  }, [locale]);

  const setLanguage = (nextLocale) => {
    if (translations[nextLocale]) {
      setLocale(nextLocale);
    }
  };

  return (
    <LanguageContext.Provider value={{ locale, setLanguage, t: translations[locale] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

